#!/bin/bash
cd build
rm -Rf *
mkdir armv7
mkdir armv7s
mkdir arm64
mkdir i386
mkdir x86_64
mkdir tvos
mkdir tvossim
cd armv7
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=OS -DENABLE_BITCODE=0 -DIOS_ARCH=armv7 ../..
make -j2
cd ../armv7s
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=OS -DENABLE_BITCODE=0 -DIOS_ARCH=armv7s ../..
make -j2
cd ../arm64
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=OS -DENABLE_BITCODE=0 -DIOS_ARCH=arm64 ../..
make -j2
cd ../i386
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=SIMULATOR -DENABLE_BITCODE=0 ../..
make -j2
cd ../x86_64
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=SIMULATOR64 -DENABLE_BITCODE=0 ../..
make -j2
cd ../tvos
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=TVOS -DENABLE_BITCODE=0 ../..
make -j2
cd ../tvossim
cmake -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.cmake -DIOS_PLATFORM=SIMULATOR_TVOS -DENABLE_BITCODE=0 ../..
make -j2
cd ..
mkdir -p iOS/OpenALSoft.framework
lipo armv7/libopenal.1.18.2.dylib armv7s/libopenal.1.18.2.dylib arm64/libopenal.1.18.2.dylib i386/libopenal.1.18.2.dylib x86_64/libopenal.1.18.2.dylib -output iOS/OpenALSoft.framework/OpenALSoft -create
cp ../iOSInfo.plist iOS/OpenALSoft.framework/Info.plist
mkdir -p tv/OpenALSoft.framework
lipo tvos/libopenal.1.18.2.dylib tvossim/libopenal.1.18.2.dylib -output tv/OpenALSoft.framework/OpenALSoft -create
cp ../tvOSInfo.plist tv/OpenALSoft.framework/Info.plist
